---
platform: linux

image_resource:
  type: registry-image
  source: { repository: node, tag: '10' }

inputs:
  - name: mars-monorepo

outputs:
  - name: livrable

run:
  path: /bin/sh
  args: ['angular-monorepo-concourse/ci/build.sh']
