---
resources:
  - name: mars-monorepo
    type: git
    source: { uri: 'https://github.com/imadhy/angular-monorepo-concourse.git' }

jobs:
  - name: unit-test
    plan:
      - get: mars-monorepo
        trigger: true
      - task: test
        params: { NG_CLI_ANALYTICS: 'ci' }
        file: angular-monorepo-concourse/ci/test.yml
  - name: build-pn106
    plan:
      - get: mars-monorepo
        trigger: true
        passed: [unit-test]
      # - task: run build
      #   file: angular-monorepo-concourse/ci/build.yml
  - name: build-pn107
    plan:
      - get: mars-monorepo
        trigger: true
        passed: [unit-test]
      # - task: run build
      #   file: angular-monorepo-concourse/ci/build.yml
