---
resources:
  - name: angular-monorepo-concourse
    type: git
    source: { uri: 'https://github.com/imadhy/angular-monorepo-concourse.git' }

jobs:
  - name: unit-test
    plan:
      - get: angular-monorepo-concourse
        trigger: true
      - task: test
        file: angular-monorepo-concourse/ci/test.yml
  - name: build-pn106
    plan:
      - get: angular-monorepo-concourse
        trigger: true
        passed: [unit-test]
      - task: run build
        file: angular-monorepo-concourse/ci/build_106.yml
  - name: build-pn107
    plan:
      - get: angular-monorepo-concourse
        trigger: true
        passed: [unit-test]
      - task: run build
        file: angular-monorepo-concourse/ci/build_107.yml
